name: storeRahisi
description: Store Rahisi App, from App Rahisi Software Series.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^0.1.3
  provider: ^4.0.4
  get_it: ^4.0.0
  firebase_analytics: ^5.0.2
  firebase_core: ^0.4.0+9
  cloud_firestore: ^0.13.4+1
  firebase_auth: ^0.15.5+2
  shared_preferences: ^0.5.6+3
  intl: ^0.16.1
  barcode_scan: ^2.0.1
  barcode_flutter: ^1.1.2
  csv: ^4.0.3
  flutter_email_sender: ^3.0.1
  path_provider: ^1.6.5
  flutter_range_slider: "^1.0.1"
  logging: ^0.11.3+1
  # sticky_headers: ^0.1.8+1
dev_dependencies:
  flutter_test:
    sdk: flutter
  # intl_translation: 0.17.10
  flutter_launcher_icons: "^0.7.3"



flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/applogo.png"


flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/i18n/en.json
    - assets/i18n/sw.json
    - assets/images/








    #  - assets/address.json


  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
    - family:  LinearIcons
      fonts:
       - asset: assets/fonts/LinearIcons.ttf

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

